image: maven:3-jdk-8

pipelines:

    branches:
        stable:
           - step:
              name: Build
              caches:
                - maven
              script:
                - mvn clean package -Dmaven.test.skip=True -e -X  # Builds the WAR
                - file=(target/*.war) # Gets the path for the WAR  
                - echo "BITBUCKET_BUILD_NUMBER $BITBUCKET_BUILD_NUMBER  BITBUCKET_BRANCH $BITBUCKET_BRANCH $file"
        