image: maven:3-jdk-8

pipelines:

    branches:
        stable:
           - step:
              name: Build
              caches:
                - maven
              script:
                - mvn -B -Dmaven.test.skip=True  package  # Builds the WAR
                - mv /opt/atlassian/pipelines/agent/build/target/oscar-14.0.0-SNAPSHOT.war /opt/atlassian/pipelines/agent/build/target/oscar-19.$BITBUCKET_BUILD_NUMBER.war
                - curl -X POST "https://${BITBUCKET_USERNAME}:${BITBUCKET_APP_PASSWORD}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"/opt/atlassian/pipelines/agent/build/target/oscar-19.$BITBUCKET_BUILD_NUMBER.war"

        