image: maven:3-jdk-8

pipelines:

    branches:
        stable:
           - step:
              name: Build
              caches:
                - maven
              script:
                - mvn -B -Dmaven.test.skip=True  package  # Builds the WAR
                - file=(target/*.war) # Gets the path for the WAR  
                - mv /opt/atlassian/pipelines/agent/build/target/oscar-14.0.0-SNAPSHOT.war /opt/atlassian/pipelines/agent/build/target/oscar-19.$BITBUCKET_BUILD_NUMBER.war
                - echo "BITBUCKET_BUILD_NUMBER $BITBUCKET_BUILD_NUMBER  BITBUCKET_BRANCH $BITBUCKET_BRANCH $file"
        